### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by naissa12** [mrafiqk/html-pdf-node#1] opened 2020-08-02 13:54 UTC
I am seeing the following error when using this library. Can someone help?

```

2020-08-02T13:51:08.989142+00:00 app[web.1]: Error: Failed to launch the browser process!
2020-08-02T13:51:08.989144+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
2020-08-02T13:51:08.989145+00:00 app[web.1]: 
2020-08-02T13:51:08.989145+00:00 app[web.1]: 
2020-08-02T13:51:08.989146+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2020-08-02T13:51:08.989147+00:00 app[web.1]: 
2020-08-02T13:51:08.989147+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
2020-08-02T13:51:08.989148+00:00 app[web.1]: at Interface.helper_js_1.helper.addEventListener (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
2020-08-02T13:51:08.989148+00:00 app[web.1]: at Interface.emit (events.js:194:15)
2020-08-02T13:51:08.989149+00:00 app[web.1]: at Interface.close (readline.js:397:8)
2020-08-02T13:51:08.989152+00:00 app[web.1]: at Socket.onend (readline.js:173:10)
2020-08-02T13:51:08.989152+00:00 app[web.1]: at Socket.emit (events.js:194:15)
2020-08-02T13:51:08.989153+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1107:12)
2020-08-02T13:51:08.989154+00:00 app[web.1]: at process.internalTickCallback (internal/process/next_tick.js:72:19)


```

**Comment by Siddharthosatwal** [comment] 2020-08-17 14:12
The same issue is faced by me when I deployed it on the Google Cloud Run. Can someone share their experience here?

**Comment by mrafiqk** [comment] 2020-09-08 10:56
@naissa12 Can you share your sample code so that I will assist you.
Thanks.

**Comment by mrafiqk** [comment] 2020-12-13 04:34
@naissa12 Duplicate of mrafiqk/html-pdf-node#3 So I am closing this issue

**Closed by mrafiqk** 2020-12-13 04:34 UTC
